"""Builds registry/datasets.json (machine) and DATA_REGISTRY.md (human)
from the raw files, their provenance (data/metadata/sources.json), validation
flags and reviewed exclusions. Deterministic: re-run any time."""

import fnmatch
import json

import pandas as pd

from src.config import BASE_DIR, DATA_DIR
from src.data_loader import load_csv
from src.datasets import exclusions_for, file_sha256, load_clean
from src.intraday.data import TF_MINUTES, validate as validate_intraday
from src.validation.daily import instrument_of, validate_daily

REGISTRY_JSON = BASE_DIR / "registry" / "datasets.json"
REGISTRY_MD = BASE_DIR / "DATA_REGISTRY.md"
SOURCES = json.load(open(DATA_DIR / "metadata" / "sources.json"))


def source_for(rel):
    for key, s in SOURCES.items():
        if key.startswith("_"):
            continue
        pats = s["match"]
        if "{" in pats:
            stem, alts = pats.split("{")
            pats = [stem + a + ".csv" for a in alts.rstrip("}.csv").split(",")]
        else:
            pats = [pats]
        if any(fnmatch.fnmatch(rel, p) for p in pats):
            return key, s
    return "unregistered", {"provider": "UNKNOWN", "license": "unknown"}


def frequency_of(name):
    for tag in ("m15", "m30", "h1", "h4", "d1"):
        if name.endswith(tag + ".csv"):
            return tag
    return "d1"


def describe(path):
    rel = str(path.relative_to(DATA_DIR))
    src_key, src = source_for(rel)
    freq = frequency_of(path.name)
    raw = load_csv(path.name, sort=False)
    sha = file_sha256(path)
    entry = {
        "dataset_id": f"{path.stem}@{sha[:12]}", "file": f"data/{rel}", "status": "raw",
        "sha256": sha, "bytes": path.stat().st_size, "source_group": src_key, **{
            k: src.get(k, "unknown") for k in ("provider", "url", "retrieved", "timezone",
                                               "price_basis", "license", "transformations")},
        "frequency": freq, "instrument": instrument_of(path.name) or path.stem,
        "rows": len(raw), "start": str(raw["date"].min()), "end": str(raw["date"].max()),
        "zero_volume_pct": round(float((raw["volume"] == 0).mean() * 100), 1),
    }
    if freq == "d1":
        flags = validate_daily(raw, path.name)
        entry["validation"] = flags["rule"].value_counts().to_dict()
        ex = exclusions_for(path.name)
        if len(ex):
            clean, prov = load_clean(path.name)
            entry["clean"] = {"dataset_id": f"{path.stem}.clean@{prov['clean_sha256'][:12]}",
                              "sha256": prov["clean_sha256"], "rows": prov["rows_clean"],
                              "exclusions": prov["exclusion_ids"]}
    else:
        rep = validate_intraday(raw, TF_MINUTES[freq], path.stem,
                                session_grid=entry["instrument"] != "XAUUSD")
        entry["validation"] = {"errors": rep["errors"], "warnings": rep["warnings"],
                               "sessions": rep.get("sessions"),
                               "incomplete_sessions": len(rep.get("incomplete_sessions", []))}
    serious = {"V01", "V02", "V03", "V05", "V07", "V08", "V10"}
    v = entry["validation"]
    if isinstance(v, dict) and "errors" in v:
        entry["validation_status"] = "FAIL" if v["errors"] else ("WARN" if v["warnings"] else "PASS")
    else:
        unresolved = serious & set(v) and not entry.get("clean")
        entry["validation_status"] = "FAIL" if unresolved else ("WARN" if v else "PASS")
    return entry


def build():
    files = sorted(p for p in DATA_DIR.rglob("*.csv")
                   if "backups" not in p.parts and "metadata" not in p.parts and "raw" not in p.parts)
    entries = [describe(p) for p in files]
    REGISTRY_JSON.parent.mkdir(exist_ok=True)
    json.dump(entries, open(REGISTRY_JSON, "w"), indent=1)
    write_md(entries)
    return entries


def write_md(entries):
    lines = ["# Data registry", "",
             "_Generated by `python3 -m src.registry.data_registry` from `registry/datasets.json` - do not edit by hand._",
             "Provenance: `data/metadata/sources.json` · exclusions: `data/metadata/exclusions.csv` · "
             "method: [METHODOLOGY.md](METHODOLOGY.md#data).", "",
             "Raw files are never modified. `clean` = raw minus reviewed exclusions (computed at load time).", "",
             "| dataset_id | freq | rows | range | validation | clean version | provider | licence |",
             "|---|---|---|---|---|---|---|---|"]
    for e in entries:
        clean = f"{e['clean']['dataset_id']} (-{e['rows'] - e['clean']['rows']} rows)" if e.get("clean") else "-"
        lines.append(f"| `{e['dataset_id']}` | {e['frequency']} | {e['rows']:,} | {e['start'][:10]} → {e['end'][:10]} "
                     f"| {e['validation_status']} | {clean} | {e['provider'][:60]} | {e['license'][:40]} |")
    lines += ["", "## Source groups", ""]
    for k, s in SOURCES.items():
        if not k.startswith("_"):
            lines.append(f"- **{k}** (`{s['match']}`): {s['provider']}; retrieved {s['retrieved']}; "
                         f"timezone {s['timezone']}; basis {s['price_basis']}; licence: {s['license']}.")
    lines += ["", "## Known limitations", "",
              "- Yahoo data: exploratory only; not established as suitable for publication.",
              "- No survivorship-free universe; all equities are today's large-caps (SURVIVORSHIP BIAS LIMITATION).",
              "- No dividends in any price series; no corporate-action file beyond `instruments.json` notes.",
              "- Index intraday volume is zero (VWAP/volume features unusable for indices).",
              "- m30/h4 files are on a 09:00 grid and are not used for intraday research.",
              "- HFT RESEARCH — DATA NOT YET AVAILABLE (no tick/order-book data)."]
    REGISTRY_MD.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    for e in build():
        print(f"{e['dataset_id']:32s} {e['validation_status']:4s} {e['provider'][:40]}")
